#! /bin/bash
complete -W "all parallel nuke enable disable" 2web
complete -W "update parallel nuke enable disable" graph2web
complete -W "update parallel nuke enable disable" weather2web
complete -W "update parallel nuke enable disable" music2web
complete -W "update parallel nuke enable disable" comic2web
complete -W "update parallel nuke enable disable" nfo2web
